[package]
authors = ["basie <basie@buckyball.digital>"]
edition = "2021"
name = "cloud_game"
version = "0.2.5"

[dependencies]
bevy = { version = "0.12.1", features = ["wayland", "wav"] }
cloud_lib = { path = "../cloud_lib", version = "0.2.4" }

[features]
dev = [
    "bevy/dynamic_linking",
]
