[package]
name = "cloud_lib"
version = "0.2.10"
edition = "2021"

[dependencies]
bevy = { version = "0.12.1", features = ["wayland", "wav"] }
bevy_rand = { version = "0.4", features = ["rand_chacha"] }
rand = "0.8"

[features]
dev = [
    "bevy/dynamic_linking",
]
